networks:
   cache-training-network:
      driver: bridge

volumes:
  redis:
  mssql_data:

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
        - mssql
        - redis
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__SqlServer: "Server=mssql,1433;Database=CacheProduct;User Id=sa;Password=Shinjuuichidesu@11;TrustServerCertificate=True"
      ConnectionStrings__RedisConnection: "redis:6379"
    networks:
      - cache-training-network
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Shinjuuichidesu@11"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - cache-training-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/opt/redis
    networks:
      - cache-training-network